### ISSUE TITLE
add SSM parameter store hashmap to services

### ISSUE THREAD

**Issue by jonboulle** [blinkist/terraform-aws-airship-ecs-service#14]
It would be nice if airship modules could automatically populate entries in the SSM parameter store encrypted with a key available to the ECS service's role. For example, if I had something like:
```
 module "web-kms" {
   source  = "blinkist/airship-kms/aws"
   version = "0.3.0"
   name    = "web"
 }

module "demo_web" {
  source  = "blinkist/airship-ecs-service/aws"
  name = "demo-web
  ...
  ssm_parameters {
     foo = "bar"
     abc = "def"
  }
  ...
}
```
then airship would automatically create resource definitions like:
```
resource "aws_ssm_parameter" "web_parameter_foo" {
  name   = "/application/${module.web-kms.name}/foo"
  type   = "SecureString"
  key_id = "${module.web-kms.aws_kms_alias_arn}"
  value  = "bar"
}

resource "aws_ssm_parameter" "web_parameter_abc" {
  name   = "/application/${module.web-kms.name}/abc"
  type   = "SecureString"
  key_id = "${module.web-kms.aws_kms_alias_arn}"
  value  = "def"
}
```
This almost makes sense with the current interface because we already pass in ssm_paths and give the module's role access to them. However, there's a missing link here between the `${module.web-kms.name}` and this module, so the example above wouldn't quite be satisfactory.

**Comment by maartenvanderhoef** [comment]
This could get messy when having multiple services sharing the same params. I personally think  that a separate module for this would make more sense.

```
module "demo_params" {
  source  = "blinkist/airship-ssm/aws"
  name = "${module.web-kms.name}"
  
  ssm_parameters {
     foo = "bar"
     abc = "def"
   }
}
```
Or use [Cloudposse parameter store](https://github.com/cloudposse/terraform-aws-ssm-parameter-store)
