### ISSUE TITLE
use terraform-aws-ecs-container-definition?

### ISSUE THREAD

**Issue by jonboulle** [blinkist/terraform-aws-airship-ecs-service#16]
instead of doing our own templating, this could be a more structured way of generating them: https://github.com/cloudposse/terraform-aws-ecs-container-definition

**Comment by maartenvanderhoef** [comment]
Yeah we can include something like that, but with on/off map merge of the portmapping block, hostname block, volumes etc.

**Comment by maartenvanderhoef** [comment]
https://github.com/blinkist/terraform-aws-airship-ecs-service/tree/with_ecs_container_definition_module WIP, the question is what do we do with the muli-container support we currently still have. Drop it completely ?

**Comment by maartenvanderhoef** [comment]
Hey @osterman, welcome to Airship space :-) .. AWS dropped multiple containers inside one task for Fargate, but still supports it for regular ECS. In the long run I'd like to see this to disappear completely as I don't see the need for it and makes tf modules unnecessary complicated.

One possible use case however would be something like:

[ECS TASK [ Container 1 : Nginx Oauth proxy  ] -link- [ Container 2 : Application server ]]

But this can also be done with using different services tbh.

**Comment by tamsky** [comment]
> But this can also be done with using different services tbh.

Care to elaborate on this?
I have a sidekick container pattern I'd like to implement using #airship, but I'm not sure if it's possible.
