### ISSUE TITLE
Add more output variables

### ISSUE THREAD

**Issue by LukGerman** [blinkist/terraform-aws-airship-ecs-service#41]
It would be nice to have more output variables.

Use case:
- adding one-off task execution for things like database migrations that can be run during CI builds

Examples:
- tasks role arn
- task execution role arn
- task defitnion arn
- task definition name

**Comment by maartenvanderhoef** [comment]
Hi @LukGerman,

I agree those outputs should be added, are you willing to contribute yourself ?

**Comment by LukGerman** [comment]
#42

**Comment by maartenvanderhoef** [comment]
Closed by https://github.com/blinkist/terraform-aws-airship-ecs-service/pull/42
