### ISSUE TITLE
Support non-ALB ECS service

### ISSUE THREAD

**Issue by bsAdvanon** [blinkist/terraform-aws-airship-ecs-service#62]
## what
* The problem is that I'd like to use just one module for both ALB ECS services as well as non-ALB services.
* An input variable should be used as a conditional/flag for .

## why
* It's not a problem per-se, but rather a feature request.
* A simple/unified interface to know/learn and reference to a single module instead of multiple modules by multiple owners/maintainers.

**Comment by maartenvanderhoef** [comment]
hi @bsAdvanon, have you checked https://airship.tf/guide/ecs_service/load_balancing.html#none ?

**Comment by bsAdvanon** [comment]
thanks @maartenvanderhoef
