### ISSUE TITLE
Problems scaling in services

### ISSUE THREAD

**Issue by faester** [blinkist/terraform-aws-airship-ecs-service#79]
## what
* We are consistently seeing that scale down events are not respected as Cloudwatch reports an error with an empty string as error message.
* We need scale downs to work to ensure we can gain true elasiticity - right now the service only scales up. 

## Reproducing 
When giving a service two scaling rules, the services scales out ok, but does not scale in afterwards. 

The rules - with very aggressive scaling rules to trigger scaling. The problem has also been reproduced using conservative scaling rules in production. 
```
scaling_rules = [
    {
      type               = "CPUUtilization"
      direction          = "up"
      evaluation_periods = "2"
      observation_period = "60"
      statistic          = "Average"
      threshold          = "70"
      cooldown           = "60"
      adjustment_type    = "ChangeInCapacity"
      scaling_adjustment = "1"
    },
    {
      type               = "CPUUtilization"
      direction          = "down"
      evaluation_periods = "2"
      observation_period = "60"
      statistic          = "Average"
      threshold          = "60"
      cooldown           = "60"
      adjustment_type    = "ChangeInCapacity"
      scaling_adjustment = "-1"
    },
  ]
```
The error message in Cloudwatch: 
```
Failed to execute action arn:aws:autoscaling:eu-west-1:648870945036:scalingPolicy:88535f9d-fa4b-4f2b-b0d5-ff7bbf816859:resource/ecs/service/trackprod/jppolid-track:policyName/trackprod-jppolid-track-CPUUtilization-scale_in. Received error: ""
```

It seems the rules produced are simply invalid for scaling in, althouth they are accepted by the AWS provider in terraform. Trying to editing the rules in the console also generates many errors about invalid syntax in rules etc.

**Comment by faester** [comment]
This is an attemped fix: https://github.com/blinkist/terraform-aws-airship-ecs-service/pull/78

**Comment by maartenvanderhoef** [comment]
Hi Morten @faester ! I  I've merged your PR. Thanks! It might be that for the 0.12 module the scaling needs to be reassessed and re-done if you have anything to mention for the sake of a better module let me know on Slack! Cheers.
